language: c
compiler: gcc
before_install:
- sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
- sudo apt-get -qq update
- sudo apt-get install -y libsdl2-dev
- sudo apt-get install -y libsdl2-mixer-dev

