language: c
compiler: gcc
before_install:
- sudo apt-add-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe"
- sudo apt-get update
- sudo apt-get install -y libsdl2-2.0-0
- sudo apt-get install -y libsdl2-mixer-2.0-0
script: make
